### PR TITLE
Contract release 1.0.0

### PR DESCRIPTION
**Pull request by fleupold**
(Reauthoring #44 under a new branch name)

Contains deployments for release!

Note that while deployment is not deterministic the contracts happen to have the same addresses for this release (this cannot be relied on).

All deployments were verified (mainnet etherscan & gnosisscan doesn't show it yet, I will monitor if this is just a caching issue)

- Barn (0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93)
  - [Goerli](https://goerli.etherscan.io/address/0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93#code)
  - [GChain](https://blockscout.com/xdai/mainnet/address/0xD02De8Da0B71E1B59489794F423FaBBa2AdC4d93/contracts#address-tabs)
  - [Mainnet](https://etherscan.io/address/0xd02de8da0b71e1b59489794f423fabba2adc4d93#code)
- Prod (0x40A50cf069e992AA4536211B23F286eF88752187)
  - [Goerli](https://goerli.etherscan.io/address/0x40A50cf069e992AA4536211B23F286eF88752187#code)
  - [GChain](https://blockscout.com/xdai/mainnet/address/0x40A50cf069e992AA4536211B23F286eF88752187/contracts#address-tabs)
  - [Mainnet](https://etherscan.io/address/0x40A50cf069e992AA4536211B23F286eF88752187#code)

### CODE REVIEW

**Review by fedgiac — APPROVED** [review]
Thanks!
I checked the deployment parameters and skimmed the verified code and everything looks good. Blockscout has now verified the contracts but mainnet is still missing.

(I'm a bit surprised some deployments have receipts and some not, but I suppose it's unrelated to the contract itself.)

**Comment by fleupold** [comment]
> (I'm a bit surprised some deployments have receipts and some not, but I suppose it's unrelated to the contract itself.)

In some deployments the script itself crashed but the logs looked ok and the transaction went through (it just couldn't get the receipt). I agree, I don't think it's a problem.

**Review by anxolin — APPROVED** [review]
It would be amazing if we can also verify the smart contract in Etherscan and Gnosis Scan

**Comment by fleupold** [comment]
> It would be amazing if we can also verify the smart contract in Etherscan and Gnosis Scan

Done

**Comment by bh2smith** [comment]
Contracts submitted for decoding on Dune:

Screenshot 2022-12-12 at 23 59 56

**Pull request merged**
