### PR TITLE
0.0.0-rc.1

### PR DESCRIPTION
**Pull request by josojo**
Test release

### CODE REVIEW

**Comment by josojo** [comment]
Sorry, I forgot this PR. I think its good to have the contract updated and get the PR merged. Probably, we can also keep the goerli deployment for a long time

**Comment by fedgiac** [comment]
It looks like Foundry changed the format of how deployments are stored. I ran `foundryup` to update and now if I execute the deploy script I see `run-latest.json` instead of `deployments.json`. Also, this seems to have broken script verification as I'm unable to verify contracts after running the script. I suppose the related issue is 3548 at [foundry-rs/foundry/issues](https://github.com/foundry-rs/foundry/issues/).
Could you please **not update** and then run the command in the readme to verify the contract?
Later I'm going to update our deployment process to account for the Foundry changes (I'll wait a bit hoping that the bug is fixed).

**Comment by josojo** [comment]
>It looks like Foundry changed the format of how deployments are stored. I ran foundryup to update and now if I execute the deploy script I see run-latest.json instead of deployments.json.

No, this was just a manual copy from run-latest.json to deployments.json, as I did it before. Sorry, I forgot that you have now the autocreation of networks.  Let me fix this.

**Comment by fedgiac** [comment]
No worries, I thought this was the default name from Foundry. The script just takes any file in there regardless of its name.
Still, verification isn't as easy as it used to be, unfortunately. I'll verify manually.

**Review by fedgiac — APPROVED** [review]

**Pull request merged**
