### PR TITLE
edit comment above validTo to add clarity

### PR DESCRIPTION
**Pull request by hking2**
Wording of previous comment was confusing, as "latest timestamp" can also refer to the most recent.

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
I'm fine with this, but its ultimately not my decision. Also, it does not appear the CLA has been triggered for this contribution.

**Comment by hking2** [comment]
Is there something I need to do on my end in regards to the CLA?

**Comment by bh2smith** [comment]
cc @nlordell and/or @fedgiac

**Comment by fedgiac** [comment]
Thank you for your contribution!
Our company policy requires any contributor to sign a CLA (like for example [like this](https://github.com/cowprotocol/services/pull/1307)). The CLA bot is currently not set up so it didn't request any signature.
Once #49 is merged, can you please rebase your commit on top of it and follow the CLA procedure?
After this is done I'll merge this PR.

**Comment by hking2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hking2** [comment]
recheck

**Review by fedgiac — APPROVED** [review]

**Pull request merged**
